version: '3.8'

services:
  db:
    image: mysql:8
    container_name: my_php_app_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=my_app_db
      - MYSQL_USER=my_app_user
      - MYSQL_PASSWORD=my_app_password
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  awscollector:
    image: amazon/aws-otel-collector
    command: ["--config=/otel-config.yaml"]
    volumes:
      - ./collector.yaml:/otel-config.yaml
      - ./log:/log/otel
    environment:
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=

    ports:
     - '4316:4316'
     - '13133:13133'

  php:
    container_name: my_php_app
    image: php:latest
    depends_on:
      - db
    ports:
      - "8000:8080"
    environment:
      # MySQL DB environment
      - DB_HOST=127.0.0.1
      - DB_NAME=my_app_db
      - DB_USER=my_app_user
      - DB_PASS=my_app_password

      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=

      # OTel environment
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_SERVICE_NAME=php-sample-ec2
      - OTEL_TRACES_EXPORTER=console
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://awscollector:4316/v1/traces
      - OTEL_PROPAGATORS=baggage,tracecontext
      # - OTEL_PHP_DISABLED_INSTRUMENTATIONS=slim,guzzle
      # If collector is in the same docker-compose, add it there & link it
      # or update the endpoint to your external service if needed

      # Additional settings
      # - OTEL_LOGS_EXPORTER=otlp
      # - OTEL_METRICS_EXPORTER=otlp
      # - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=dev
