version: '3.8'

services:
  db:
    image: mysql:8
    container_name: my_php_app_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=my_app_db
      - MYSQL_USER=my_app_user
      - MYSQL_PASSWORD=my_app_password
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  php:
    build: .
    container_name: my_php_app
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    network_mode: "host"
    environment:
      # MySQL DB environment
      - DB_HOST=127.0.0.1
      - DB_NAME=my_app_db
      - DB_USER=my_app_user
      - DB_PASS=my_app_password

      # OTel environment
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_SERVICE_NAME=php-sample-ec2
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4316
      - OTEL_PROPAGATORS=baggage,tracecontext
      # If collector is in the same docker-compose, add it there & link it
      # or update the endpoint to your external service if needed

      # Additional settings
      # - OTEL_LOGS_EXPORTER=otlp
      # - OTEL_METRICS_EXPORTER=otlp
      # - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=dev
